from Class import StorageLocation
import constant.storage as STORAGE_CONSTANT
import constant.home as HOME_CONSTANT
import constant.colors as COLORS_CONSTANT

STORAGE_CONFIG = [
    # GOLDEN
    
    # LIGNE 1
    StorageLocation("SAC_POINT_FARM", STORAGE_CONSTANT.CHEST_SAC_POINT_FARM, "Sac de points farm", HOME_CONSTANT.GOLDEN),
    
    StorageLocation("BOITE_BOOST", STORAGE_CONSTANT.CHEST_BOITE_BOOST, ["Boite", "boosts"], HOME_CONSTANT.GOLDEN),
    
    StorageLocation("BOITES_PETS", STORAGE_CONSTANT.CHEST_BOITES_PETS, ["Boite", "familiers"], HOME_CONSTANT.GOLDEN, exclude_patterns="bonbons"),
    
    StorageLocation("RUNES_OUTILS", STORAGE_CONSTANT.CHEST_RUNES_OUTILS, "farmdariaomnitool:rune_id", HOME_CONSTANT.GOLDEN),
    StorageLocation("SAC_RUNES_OUTILS", STORAGE_CONSTANT.CHEST_RUNES_OUTILS, "Sac de Runes", HOME_CONSTANT.GOLDEN),
    
    
    # LIGNE 2
    StorageLocation("SAC_AMES", STORAGE_CONSTANT.CHEST_SAC_AMES, ["Sac d", "mes"], HOME_CONSTANT.GOLDEN),
    
    StorageLocation("ARMES", STORAGE_CONSTANT.CHEST_ARMES, ["minecraft:", "sword"], HOME_CONSTANT.GOLDEN),
    StorageLocation("ARMES", STORAGE_CONSTANT.CHEST_ARMES, "minecraft:bow", HOME_CONSTANT.GOLDEN),
    StorageLocation("PARCHEMIN_EXTRACTION", STORAGE_CONSTANT.CHEST_ARMES, ["Parchemin", "extraction"], HOME_CONSTANT.GOLDEN),
    StorageLocation("AMULETTE", STORAGE_CONSTANT.CHEST_ARMES, "Amulette", HOME_CONSTANT.GOLDEN),
    StorageLocation("COLLIER", STORAGE_CONSTANT.CHEST_ARMES, "Collier", HOME_CONSTANT.GOLDEN),
    StorageLocation("BAGUE", STORAGE_CONSTANT.CHEST_ARMES, "Bague", HOME_CONSTANT.GOLDEN),
    
    StorageLocation("PETS_LEGENDAIRE", STORAGE_CONSTANT.CHEST_PETS, ["companions:pet-id", COLORS_CONSTANT.LEGENDARY], HOME_CONSTANT.GOLDEN),
    StorageLocation("PETS_MYTHIQUE", STORAGE_CONSTANT.CHEST_PETS, ["companions:pet-id", COLORS_CONSTANT.MYTHIQUE], HOME_CONSTANT.GOLDEN),
    
    #StorageLocation("RUNE_COMBAT", STORAGE_CONSTANT.CHEST_RUNES_COMBATS, "Glisse sur un objet pour appliquer", HOME_CONSTANT.GOLDEN),
    StorageLocation("CAISSE_DE_CONTREBANDE", STORAGE_CONSTANT.CHEST_RUNES_COMBATS, "Caisse de contrebande", HOME_CONSTANT.GOLDEN),
    
    # LIGNE 3
    StorageLocation("ARMURES_BOOTS", STORAGE_CONSTANT.CHEST_ARMURES_DONJON, "minecraft:diamond_boots", HOME_CONSTANT.GOLDEN),
    StorageLocation("ARMURES_LEGGINGS", STORAGE_CONSTANT.CHEST_ARMURES_DONJON, "minecraft:diamond_leggings", HOME_CONSTANT.GOLDEN),
    StorageLocation("ARMURES_CHESTPLATE", STORAGE_CONSTANT.CHEST_ARMURES_DONJON, "minecraft:diamond_chestplate", HOME_CONSTANT.GOLDEN),
    StorageLocation("ARMURES_HELMET", STORAGE_CONSTANT.CHEST_ARMURES_DONJON, "minecraft:diamond_helmet", HOME_CONSTANT.GOLDEN),
    StorageLocation("ARMURES_NETHERITE_BOOTS", STORAGE_CONSTANT.CHEST_ARMURES_DONJON, "minecraft:netherite_boots", HOME_CONSTANT.GOLDEN),
    StorageLocation("ARMURES_NETHERITE_LEGGINGS", STORAGE_CONSTANT.CHEST_ARMURES_DONJON, "minecraft:netherite_leggings", HOME_CONSTANT.GOLDEN),
    StorageLocation("ARMURES_NETHERITE_CHESTPLATE", STORAGE_CONSTANT.CHEST_ARMURES_DONJON, "minecraft:netherite_chestplate", HOME_CONSTANT.GOLDEN),
    StorageLocation("ARMURES_NETHERITE_HELMET", STORAGE_CONSTANT.CHEST_ARMURES_DONJON, "minecraft:netherite_helmet", HOME_CONSTANT.GOLDEN),
        
    StorageLocation("ARMURES_FARM_BOOTS", STORAGE_CONSTANT.CHEST_ARMURES_FARM, "minecraft:leather_boots", HOME_CONSTANT.GOLDEN),
    StorageLocation("ARMURES_FARM_LEGGINGS", STORAGE_CONSTANT.CHEST_ARMURES_FARM, "minecraft:leather_leggings", HOME_CONSTANT.GOLDEN),
    StorageLocation("ARMURES_FARM_CHESTPLATE", STORAGE_CONSTANT.CHEST_ARMURES_FARM, "minecraft:leather_chestplate", HOME_CONSTANT.GOLDEN),
    StorageLocation("ARMURES_FARM_MASQUE", STORAGE_CONSTANT.CHEST_ARMURES_FARM, "Masque de ", HOME_CONSTANT.GOLDEN),
    
    
    # LIGNE 4
    StorageLocation("CLEF_FRAGMENTEE_LEGENDAIRE", STORAGE_CONSTANT.CHEST_CLEF_LEG_COSMETIQUE, ["gendaire", "Assemble six fragments pour"], HOME_CONSTANT.GOLDEN),
    StorageLocation("CLEF_FRAGMENTEE_COSMETIQUE", STORAGE_CONSTANT.CHEST_CLEF_LEG_COSMETIQUE, ["Cosm", "tiques", "Assemble six fragments pour"], HOME_CONSTANT.GOLDEN),
    
    StorageLocation("CLEF_DONJON", STORAGE_CONSTANT.CHEST_CLEF_DONJON, ["Assemble six fragments pour", "de donjon"], HOME_CONSTANT.GOLDEN),
    StorageLocation("CLEF_HALLOWEEN", STORAGE_CONSTANT.CHEST_CLEF_DONJON, ["Assemble fix fragments pour", "halloween"], HOME_CONSTANT.GOLDEN),
    
    # LIGNE 5
    StorageLocation("CLEF_FRAGMENTEE_EPIQUE", STORAGE_CONSTANT.CHEST_CLEF_EPIC, ["Epique", "Assemble six fragments pour"], HOME_CONSTANT.GOLDEN),
    
    StorageLocation("SLOT_GENERATEUR", STORAGE_CONSTANT.CHEST_SLOT_GENS, ["Slot de g", "rateur"], HOME_CONSTANT.GOLDEN),
    
    # LIGNE 6
    StorageLocation("CLEF_FRAGMENTEE_RARE", STORAGE_CONSTANT.CHEST_CLEF_RARE, ["Rare", "Assemble six fragments pour"], HOME_CONSTANT.GOLDEN),
    
    StorageLocation("POTION_DONJON", STORAGE_CONSTANT.CHEST_POTION_DONJON, ["Consomme cette potion", "afin de r"], HOME_CONSTANT.GOLDEN),
    
     
    
    # JETONS
    
    StorageLocation("SAC_JETON_COMMUN", [STORAGE_CONSTANT.CHEST_JETON_T1_1, STORAGE_CONSTANT.CHEST_JETON_T1_2, STORAGE_CONSTANT.CHEST_JETON_T1_3], ["Sac de jetons", COLORS_CONSTANT.COMMUN], HOME_CONSTANT.JETON),
    StorageLocation("SAC_JETON_PEU_COMMUN", [STORAGE_CONSTANT.CHEST_JETON_T2_1, STORAGE_CONSTANT.CHEST_JETON_T2_2, STORAGE_CONSTANT.CHEST_JETON_T2_3], ["Sac de jetons", COLORS_CONSTANT.PEU_COMMUN], HOME_CONSTANT.JETON),
    StorageLocation("SAC_JETON_RARE", [STORAGE_CONSTANT.CHEST_JETON_T3_1, STORAGE_CONSTANT.CHEST_JETON_T3_2, STORAGE_CONSTANT.CHEST_JETON_T3_3], ["Sac de jetons", COLORS_CONSTANT.RARE], HOME_CONSTANT.JETON),
    StorageLocation("SAC_JETON_EPIC", [STORAGE_CONSTANT.CHEST_JETON_T4_1, STORAGE_CONSTANT.CHEST_JETON_T4_2, STORAGE_CONSTANT.CHEST_JETON_T4_3], ["Sac de jetons", COLORS_CONSTANT.EPIC], HOME_CONSTANT.JETON),
    StorageLocation("SAC_JETON_MYTHIQUE", [STORAGE_CONSTANT.CHEST_JETON_T4_1, STORAGE_CONSTANT.CHEST_JETON_T4_2, STORAGE_CONSTANT.CHEST_JETON_T4_3], ["Sac de jetons", COLORS_CONSTANT.MYTHIQUE], HOME_CONSTANT.JETON),
    
    
    
    # XP
    
    StorageLocation("SAC_XP_COMMUN", [STORAGE_CONSTANT.CHEST_XP_T1_1, STORAGE_CONSTANT.CHEST_XP_T1_2, STORAGE_CONSTANT.CHEST_XP_T1_3], ["EXP Outil", COLORS_CONSTANT.COMMUN], HOME_CONSTANT.XP),
    StorageLocation("SAC_XP_PEU_COMMUN", [STORAGE_CONSTANT.CHEST_XP_T2_1, STORAGE_CONSTANT.CHEST_XP_T2_2, STORAGE_CONSTANT.CHEST_XP_T2_3], ["EXP Outil", COLORS_CONSTANT.PEU_COMMUN], HOME_CONSTANT.XP),
    StorageLocation("SAC_XP_RARE", [STORAGE_CONSTANT.CHEST_XP_T3_1, STORAGE_CONSTANT.CHEST_XP_T3_2, STORAGE_CONSTANT.CHEST_XP_T3_3], ["EXP Outil", COLORS_CONSTANT.RARE], HOME_CONSTANT.XP),
    StorageLocation("SAC_XP_EPIC", [STORAGE_CONSTANT.CHEST_XP_T4_1, STORAGE_CONSTANT.CHEST_XP_T4_2, STORAGE_CONSTANT.CHEST_XP_T4_3], ["EXP Outil", COLORS_CONSTANT.EPIC], HOME_CONSTANT.XP),
    StorageLocation("SAC_XP_MYTHIQUE", [STORAGE_CONSTANT.CHEST_XP_T4_1, STORAGE_CONSTANT.CHEST_XP_T4_2, STORAGE_CONSTANT.CHEST_XP_T4_3], ["EXP Outil", COLORS_CONSTANT.MYTHIQUE], HOME_CONSTANT.XP),
    
    
    # COGS
    
    StorageLocation("COGS_COMMUN", [STORAGE_CONSTANT.CHEST_COGS_T1_1, STORAGE_CONSTANT.CHEST_COGS_T1_2, STORAGE_CONSTANT.CHEST_COGS_T1_3], ["Clique droit sur ton g", COLORS_CONSTANT.COMMUN], HOME_CONSTANT.COGS),
    StorageLocation("COGS_PEU_COMMUN", [STORAGE_CONSTANT.CHEST_COGS_T2_1, STORAGE_CONSTANT.CHEST_COGS_T2_2, STORAGE_CONSTANT.CHEST_COGS_T2_3], ["Clique droit sur ton g", COLORS_CONSTANT.PEU_COMMUN], HOME_CONSTANT.COGS),
    StorageLocation("COGS_RARE", [STORAGE_CONSTANT.CHEST_COGS_T3_1, STORAGE_CONSTANT.CHEST_COGS_T3_2, STORAGE_CONSTANT.CHEST_COGS_T3_3], ["Clique droit sur ton g", COLORS_CONSTANT.RARE], HOME_CONSTANT.COGS),
    StorageLocation("COGS_EPIC", [STORAGE_CONSTANT.CHEST_COGS_T4_1, STORAGE_CONSTANT.CHEST_COGS_T4_2, STORAGE_CONSTANT.CHEST_COGS_T4_3], ["Clique droit sur ton g", COLORS_CONSTANT.EPIC], HOME_CONSTANT.COGS),
    
    
    
    
    
    # PETS
    
    StorageLocation("PETS_COMMUN", [STORAGE_CONSTANT.CHEST_PET_T1_1, STORAGE_CONSTANT.CHEST_PET_T1_2, STORAGE_CONSTANT.CHEST_PET_T1_3], ["companions:pet-id", COLORS_CONSTANT.COMMUN], HOME_CONSTANT.PETS),
    StorageLocation("PETS_PEU_COMMUN", [STORAGE_CONSTANT.CHEST_PET_T2_1, STORAGE_CONSTANT.CHEST_PET_T2_2, STORAGE_CONSTANT.CHEST_PET_T2_3], ["companions:pet-id", COLORS_CONSTANT.PEU_COMMUN], HOME_CONSTANT.PETS),
    StorageLocation("PETS_RARE", [STORAGE_CONSTANT.CHEST_PET_T3_1, STORAGE_CONSTANT.CHEST_PET_T3_2, STORAGE_CONSTANT.CHEST_PET_T3_3], ["companions:pet-id", COLORS_CONSTANT.RARE], HOME_CONSTANT.PETS),
    StorageLocation("PETS_EPIC", [STORAGE_CONSTANT.CHEST_PET_T4_1, STORAGE_CONSTANT.CHEST_PET_T4_2, STORAGE_CONSTANT.CHEST_PET_T4_3], ["companions:pet-id", COLORS_CONSTANT.EPIC], HOME_CONSTANT.PETS),
    
    
    
    
    StorageLocation("PETS_MYTHIQUE", STORAGE_CONSTANT.CHEST_PETS, ["companions:pet-id", COLORS_CONSTANT.MYTHIQUE], HOME_CONSTANT.GOLDEN),
    
        
        
    
    # BONBON
    
    StorageLocation("BONBON_COMMUN", [STORAGE_CONSTANT.CHEST_BONBON_T1_1, STORAGE_CONSTANT.CHEST_BONBON_T1_2, STORAGE_CONSTANT.CHEST_BONBON_T1_3], ["Bonbon de familier", COLORS_CONSTANT.COMMUN], HOME_CONSTANT.BONBON),
    StorageLocation("BONBON_PEU_COMMUN", [STORAGE_CONSTANT.CHEST_BONBON_T2_1, STORAGE_CONSTANT.CHEST_BONBON_T2_2, STORAGE_CONSTANT.CHEST_BONBON_T2_3], ["Bonbon de familier", COLORS_CONSTANT.PEU_COMMUN], HOME_CONSTANT.BONBON),
    StorageLocation("BONBON_RARE", [STORAGE_CONSTANT.CHEST_BONBON_T3_1, STORAGE_CONSTANT.CHEST_BONBON_T3_2, STORAGE_CONSTANT.CHEST_BONBON_T3_3], ["Bonbon de familier", COLORS_CONSTANT.RARE], HOME_CONSTANT.BONBON),
    StorageLocation("BONBON_EPIC", [STORAGE_CONSTANT.CHEST_BONBON_T4_1, STORAGE_CONSTANT.CHEST_BONBON_T4_2, STORAGE_CONSTANT.CHEST_BONBON_T4_3], ["Bonbon de familier", COLORS_CONSTANT.EPIC], HOME_CONSTANT.BONBON),
    StorageLocation("BONBON_LEGENDAIRE", [STORAGE_CONSTANT.CHEST_BONBON_T4_1, STORAGE_CONSTANT.CHEST_BONBON_T4_2, STORAGE_CONSTANT.CHEST_BONBON_T4_3], ["Bonbon de familier", COLORS_CONSTANT.LEGENDARY], HOME_CONSTANT.BONBON),
    StorageLocation("BONBON_MYTHIQUE", [STORAGE_CONSTANT.CHEST_BONBON_T4_1, STORAGE_CONSTANT.CHEST_BONBON_T4_2, STORAGE_CONSTANT.CHEST_BONBON_T4_3], ["Bonbon de familier", COLORS_CONSTANT.MYTHIQUE], HOME_CONSTANT.BONBON),
    
    StorageLocation("BOITE_BONBON", STORAGE_CONSTANT.CHEST_BOITE_BONBON, "Boite de bonbons", HOME_CONSTANT.BONBON),
    


    # THUNE

    StorageLocation("SAC_ARGENT", STORAGE_CONSTANT.CHEST_THUNE, ["Sac d", "argent", "une somme"], HOME_CONSTANT.THUNE),
    
    #RUNE

    StorageLocation("RUNE_COMBAT", [STORAGE_CONSTANT.CHEST_RUNE_T1_1, STORAGE_CONSTANT.CHEST_RUNE_T1_2, STORAGE_CONSTANT.CHEST_RUNE_T1_3,], ["Glisse sur un objet pour appliquer", COLORS_CONSTANT.COMMUN], HOME_CONSTANT.RUNE),
    StorageLocation("RUNE_COMBAT", [STORAGE_CONSTANT.CHEST_RUNE_T2_1, STORAGE_CONSTANT.CHEST_RUNE_T2_2, STORAGE_CONSTANT.CHEST_RUNE_T2_3,], ["Glisse sur un objet pour appliquer", COLORS_CONSTANT.PEU_COMMUN], HOME_CONSTANT.RUNE),
    StorageLocation("RUNE_COMBAT", [STORAGE_CONSTANT.CHEST_RUNE_T3_1, STORAGE_CONSTANT.CHEST_RUNE_T3_2, STORAGE_CONSTANT.CHEST_RUNE_T3_3,], ["Glisse sur un objet pour appliquer", COLORS_CONSTANT.RARE], HOME_CONSTANT.RUNE),
    StorageLocation("RUNE_COMBAT", [STORAGE_CONSTANT.CHEST_RUNE_T4_1, STORAGE_CONSTANT.CHEST_RUNE_T4_2, STORAGE_CONSTANT.CHEST_RUNE_T4_3,], ["Glisse sur un objet pour appliquer", COLORS_CONSTANT.EPIC], HOME_CONSTANT.RUNE),
    StorageLocation("RUNE_COMBAT", [STORAGE_CONSTANT.CHEST_RUNE_T5_1, STORAGE_CONSTANT.CHEST_RUNE_T5_2, STORAGE_CONSTANT.CHEST_RUNE_T5_3,], ["Glisse sur un objet pour appliquer", COLORS_CONSTANT.MYTHIQUE], HOME_CONSTANT.RUNE),
    
]

